// <auto-generated />
namespace HolidayHelper.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MandRService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MandRService));
        
        string IMigrationMetadata.Id
        {
            get { return "202111130732371_MandRService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
