// <auto-generated />
namespace HolidayHelper.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update2739821 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update2739821));
        
        string IMigrationMetadata.Id
        {
            get { return "202111160645396_Update2739821"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
